### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hassanqaiser** [mraad/ExportImageSOI#1]
I tried and getting the following error,

"Could not resolve dependencies for project com.esri:ExportImageSOI:jar:0.32: The following artifacts could not be resolved: com.esri:hex-grid_2.10:jar:1.2, com.esri:webmercator_2.10:jar:1.2: Failure to find com.esri:hex-grid_2.10:jar:1.2 in https://repository.cloudera.com/artifactory/cloudera-repos was cached in the local repository, resolution will not be reattempted until the update interval of cloudera-releases has elapsed or updates are forced".

Kindly assist.

**Comment by mraad** [comment]
https://github.com/mraad/hex-grid
https://github.com/mraad/WebMercator

**Comment by hassanqaiser** [comment]
thanks....
